### ISSUE TITLE
Duplicate tiles in level editor

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#3]
Version: 0.0.1
OS: Windows 10

Everytime you press "play" while in a training room the tiletypes get added to the list, which means after opening the tiletype selection window 3 times every tiletype will be in the list 3 times.

**Comment by schematical** [comment]
Ah yeah this has to do with that bug that messes everything up when you go from playing to any other non-overlay screen such as level building

**Comment by schematical** [comment]
This should be fixed when I fixed the level reload issue. Let me know if you see it again.

**Comment by suppergerrie2** [comment]
I can still reproduce it in the latest version:

Steps to reproduce:
  1. Load level
  2. Click play in the topright
  3. Count the amount of tiles
  4. Click play twice (Close and open the tile menu)
  5. Notice the amount of tiles doubled

**Comment by suppergerrie2** [comment]
Also able to reproduce it on ubuntu, will make a video when I am back on my win10 pc

**Comment by suppergerrie2** [comment]
Fixed!
